name: annas_archive
description: A new Dart Frog application
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  annas_archive_api: ^0.0.9
  beautiful_soup_dart: ^0.3.0
  dart_frog: ^1.1.0
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  reliable_interval_timer: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
